### PR TITLE
Increase alignment of eh_frame from 8 to 32 bytes

### LINKED ISSUE #65: Exceptions not working
- [X] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Expected behavior
Should be able to obtain multiple dma handles at the same time (as used in fft.cpp).

### Actual behavior
Code crashes on attempting to obtain second handle. Root cause is that exceptions do not work .

### Test code
```c
extern int dma_open_free();

int main(void)
{
        uintptr_t dma_write = dma_open_free();
        uintptr_t dma_read = dma_open_free();

    while (1)
        ;
    return 0;
}
```
Specific exception handling test available here: https://gitlab.com/nemach-embedded/maix-pio-exceptions

### Document version
commit 45a5b641a8456b9d3623435946a92c6c2503d228 (HEAD -> develop, origin/develop, origin/HEAD)

### Hardware
MAIX Dock One

### System
Windows 10

### PR DESCRIPTION
**Pull request by nmaitland**
Fixes #65 

- [x] I have thoroughly tested my contribution.
- [x] The code I submitted has no copyright issues.

Fixes fatal sys_exit when exceptions are throw from C++ code.

### CODE REVIEW

**Comment by minux** [comment]
is this alignment the real cause? because .eh_frame section shouldn't need
anything more than pointer alignment.

**Comment by nmaitland** [comment]
@minux I had originally posted an alternative fix, where I manually moved the crtend.o file to the end of the linker command line. However I couldn't see how to make this a default part of the build chain and changing alignment of eh_frame seemed to also fix. I appreciate your input...
https://github.com/sipeed/platform-kendryte210/issues/32#issue-709019100

**Comment by minux** [comment]
crtend.o and crtn.o should usually be the last two object files
linked, and these are usually added by the g++ driver.
I'm not sure why the SDK manually links them in, perhaps the compiler
builtin spec file is wrong.

Anyway, for the current approach of manually linking these files, I think
the correct fix is to fix
https://github.com/kendryte/kendryte-freertos-sdk/blob/45a5b641a8456b9d3623435946a92c6c2503d228/cmake/toolchain.cmake#L43
so that it places \"${CRTEND_OBJ}\" \"${CRTN_OBJ}\" after <LINK_LIBRARIES>.
please also fix
https://github.com/kendryte/kendryte-freertos-sdk/blob/45a5b641a8456b9d3623435946a92c6c2503d228/cmake/toolchain.cmake#L46
for the same problem.

Thanks for working on this.

**Comment by nmaitland** [comment]
Thanks for your comments and info. I've actually been using platformio for my builds up to now and as I'm new to this platform I hadn't realised that this uses a different build chain to the core kendryte-freertos-sdk project (scons vs cmake). So I've now checked and confirm that my test works fine when built in the SDK cmake tools, and just fails with platformio.

I've now raised a ticket in https://github.com/sipeed/platform-kendryte210. Tx for helping me out here and sorry for causing unnecessary effort.

**Pull request closed without merging**
